[tool.poetry]
name = "onnx-diff"
version = "0.1.1"
description = "Work in progress..."
authors = ["magnus <contact@magnus.co.uk>"]
readme = "README.md"
repository = "https://github.com/magnusmaynard/onnx-diff"
keywords = ["onnx", "compare", "diff", "difference", "tool", "model", "ml", "ai"]

[tool.poetry.scripts]
onnxdiff = 'onnx_diff.run:run'

[tool.poetry.dependencies]
python = "^3.9"
onnx = "^1.13.0"
numpy = "^1.24.1"
GraKeL = "^0.1.9"
tabulate = "^0.9.0"
colorama = "^0.4.6"

[tool.poetry.dev-dependencies]
pytest = "^6.0"
ipdb = "^0.13.11"
requests = "^2.28.1"
pytest-cov = "^4.0.0"

[tool.pytest.ini_options]
filterwarnings = "ignore::PendingDeprecationWarning:grakel.*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
