[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "gff2bed"
version = "1.0.2" # Don't forget to match with version.py and docs/source/conf.py
authors = [
  { name="Anthony Aylward", email="aaylward@salk.edu" },
]
description = "Convert GFF3-formatted data to BED format"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://gitlab.com/salk-tm/gff2bed"
"Documentation" = "https://salk-tm.gitlab.io/gff2bed"
