[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.version]
path = "idp_authentication/__init__.py"

[project]
name = "idp_authentication"
description = "IDP Authentication - Hexagonal Architecture Implementation"
readme = "README.md"
requires-python = ">=3.9"
authors = [
    { name = "Lirim Shala", email = "lirim.shala@cardoai.com" },
    { name = "Klajdi Ã‡aushi", email = "klajdi.caushi@cardoai.com" }
]
classifiers = [
    "Intended Audience :: Information Technology",
    "Intended Audience :: System Administrators",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
dependencies = [
    "SQLAlchemy==1.4.45",
    "pydantic==1.10.2",
    "faust-streaming==0.10.0",
    "dependency-injector==4.41.0"
]
dynamic = ["version"]

[project.urls]
"Homepage" = "https://github.com/CardoAI/idp-authentication"
"Bug Tracker" = "https://github.com/CardoAI/idp-authentication/issues"

[project.optional-dependencies]
test = [
    "pytest==7.2.0",
    "black>=22.10.0",
    "isort==5.11.3",
    "pytest-cov==4.0.0",
    "autoflake==2.0.0",
]
all = [
    "SQLAlchemy==1.4.45",
    "pydantic==1.10.2",
    "faust-streaming==0.10.0",
    "dependency-injector==4.41.0"
]
docs = [
    "mkdocs-material==8.5.11",
    "mkdocstrings[python]==0.19.1",
]

[tool.black]
line-length = 88
target-version = ['py39', 'py310', 'py311']
include = '\.pyi?$'
exclude = '''
/(
  # The following are specific to Black, you probably don't want those.
  | blib2to3
  | tests/data
  | profiling
  | migrations
)/
'''

[tool.isort]
profile = "black"