[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "mose_framework"
version = "0.0.2"
description = "Managing & Organizing Science Experiments"
readme = "README.md"
requires-python = ">=3.7, <4"
license = {file = "LICENSE"}
keywords = ["mose", "test"]
authors = [
  {email = "d.oneil@columbia.edu"},
  {name = "Darik A. O'Neil"}
]
maintainers = [
    {name = "Darik A. O'Neil", email = "d.oneil@columbia.edu"}
]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Programming Language :: Python"
]

dependencies = [
    "numpy",
    "pandas",
    "ipython",
    "tqdm"
]
