[tool.poetry]
name = "subjectdb-manager"
version = "0.1.1"
description = ""
authors = ["Greg Schwimer <schwim@bitrail.com>"]
readme = "README.md"
packages = [{include = "subjectdb_manager", from = "src"}]

[tool.poetry.dependencies]
python = "^3.9"
pyyaml = "^6.0"
click = "^8.1.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
subjectdb_manager = "subjectdb_manager.subjectdb_manager:cli"
